// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FirstAPI.Data;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    [Migration("20260116110234_book data added")]
    partial class bookdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstAPI.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "f. scott fitzgerald",
                            Title = "the great gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            ID = 2,
                            Author = "harper lee",
                            Title = "to kill a mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            ID = 3,
                            Author = "george orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            ID = 4,
                            Author = "jane austen",
                            Title = "pride and prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            ID = 5,
                            Author = "herman melville",
                            Title = "moby-dick",
                            YearPublished = 1851
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
